### ISSUE TITLE
PM Review: User Auth

### ISSUE THREAD

**Issue by LochandQuay** [rebekahliu/KickStartNow#23]

**Comment by LochandQuay** [comment]
@rebekahliu can you send me your heroku link?

**Comment by rebekahliu** [comment]
https://polar-shelf-46662.herokuapp.com/#/

**Comment by LochandQuay** [comment]
@rebekahliu 

General FYI: The non-PM Review issues are for you to close as you progress through an MVP…it also helps me keep track of your progress. None of them have been closed for User Auth…try to keep those up-to-date so I know progress is being made. :)
Once all the User Auth issues are closed, the Milestone can be closed. 

Notes: 
- I don't think you're preventing default on the Demo Login button. You can tell because you're URL route changes from `/#/...` to `/?#/...`, which implies that the button tried to trigger a default action.
- Would like to see Demo Login on both login and signup forms
- Errors could use a little more styling
- Would like some acknowledgement of the user that logged in up in the nav bar (next to the logout button)
- A little nitpicky, but it's a bit weird that the Kickstartnow logo at the top shifts slightly after you log in. Might want to change that.

**Comment by LochandQuay** [comment]
@rebekahliu 

Also your password field is currently "text", when it should be "password"!

**Comment by rebekahliu** [comment]
I made all the changes above. I intentionally left out the user greeting because the kickstarter website doesn't have it and I think it makes the nav bar look more cluttered.
